### ISSUE TITLE
When will it be converted to a Non-Matlab language?

### ISSUE THREAD

**Issue by orionblastar** [facebook/MemNN#1]
I can't afford Matlab, and I can't read Matlab code. When will this get ported to a different language like Python, C++, Java, etc? I'd like to see it in use with one of the free and open source languages.

**Comment by jaseweston** [comment]
There is Torch7 (Lua) code here:
https://github.com/facebook/MemNN/tree/master/MemN2N-lang-model
There is Theano (Python) code here: https://github.com/npow/MemN2N  (we
didn't write this one)

We are working on releasing more Torch 7 code too.
