### ISSUE TITLE
Human-in-the-Loop cannot be downloaded

### ISSUE THREAD

**Issue by sparanoid** [facebook/MemNN#21]
Data in [setup_data.sh](https://github.com/facebook/MemNN/blob/master/HITL/setup_data.sh) and [setup_turk_data.sh](https://github.com/facebook/MemNN/blob/master/HITL/setup_turk_data.sh) are no longer available to download:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>AllAccessDisabled</Code>
  <Message>All access to this object has been disabled</Message> 
  <RequestId>00EC33BECAAF3FB7</RequestId>
  <HostId>3gzW5QZH/lqRs4tq5zuQcaFbrQtrjgluiSx/leIG3SW9IRtAniZZ10iW3kCZyums5G29LV9gnJs=</HostId>
</Error>
```

**Comment by chenmoshushi** [comment]
+1

**Comment by alexholdenmiller** [comment]
resolved! in general I'd recommend checking out the more up-to-date ParlAI repository for state of the art dialogue research: github.com/facebookresearch/ParlAI
