### ISSUE TITLE
Dataset can no longer be downloaded

### ISSUE THREAD

**Issue by goodboyanush** [facebook/MemNN#23]
The human annotated dataset is no longer available and without that it is difficult to reproduce the given work. Could you please provide a work around for that?

```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
  <Code>AllAccessDisabled</Code>
  <Message>All access to this object has been disabled</Message> 
  <RequestId>00EC33BECAAF3FB7</RequestId>
  <HostId>3gzW5QZH/lqRs4tq5zuQcaFbrQtrjgluiSx/leIG3SW9IRtAniZZ10iW3kCZyums5G29LV9gnJs=</HostId>
</Error>
```

**Comment by alexholdenmiller** [comment]
resolved!

**Comment by alexholdenmiller** [comment]
in general I'd recommend checking out the more up-to-date ParlAI repository for state of the art dialogue research: github.com/facebookresearch/ParlAI
