### ISSUE TITLE
can't run MemN2N-lang-model

### ISSUE THREAD

**Issue by egrcc** [facebook/MemNN#3]
Hi, 

I'm a beginner of torch. While I run the MemN2N-lang-model in my ubuntu 15.10(CUDA 7.5 is installed and my data is copied from https://github.com/wojzaremba/lstm/tree/master/data ), I get a error:

![2016-03-28 17-21-35](https://cloud.githubusercontent.com/assets/6469953/14075215/be8e3182-f509-11e5-8d35-3e982a6f2774.png)

Could you tell me what's wrong with this?

Thanks~

**Comment by soumith** [comment]
hi, i dont see the same error message. can you try to update your nn and cunn packages via:
luarocks install nn
luarocks install cunn

**Comment by tesatory** [comment]
It is working fine for me too.

**Comment by egrcc** [comment]
@soumith Works! Thanks a lot!
