### ISSUE TITLE
Cannot read "dict-hash.txt"

### ISSUE THREAD

**Issue by AndreaAI** [facebook/MemNN#5]
Hello,

I have a problem while running the file "build_hash.sh". When it tries to run "build_hash.lua", it does not detect  dictFile="./data/torch/dict-hash.txt" \, I get the error that dict-hash.txt is nil, but it has the processed information.  I cannot fix the error, do you know how can I solve it?

![error](https://cloud.githubusercontent.com/assets/27763341/26677414/23aa4dac-46cc-11e7-8af7-5bc3d9cad67d.PNG)

Thank you so much,

Andrea

**Comment by alexholdenmiller** [comment]
Hi Andrea,

Just to confirm, `ls ./data/torch/dict-hash.txt` works just fine from that same directory, yes?

**Comment by AndreaAI** [comment]
Hi,

The file is in the same directory, created with first lines of build_hash.sh (th build_dict_hash.lua \
./data/torch/dict-hash.txt ./data/torch/dict.txt ./data/entities_1.txt 10000), that works fine. But when I run the second part, it identifies the file as nil.  I used "assert" function while trying to load the dictionary and it says "no such file or directory".
 (Sorry, I am a bit inexperienced with all this stuff). Thank you!

**Comment by alexholdenmiller** [comment]
First off, let me check: from the readme, you don't need to build the hash yourself if you ran `setup_processed_data.sh`.

Otherwise, then you've done the following already (from the readme)...
```bash
./setup_data.sh
./gen_wiki_windows.sh
./gen_multidict_questions.sh
./build_dict.sh
./build_data.sh
```
...and that all worked fine?

In which case now you're trying to run `build_hash.sh`, and...
```bash
th build_dict_hash.lua ./data/torch/dict-hash.txt ./data/torch/dict.txt ./data/entities_1.txt 1000000`
```
...worked, but...
```bash
th ../../scripts/build_hash.lua params \
"./data/torch/wiki-w=0-d=3-i-m.txt.hash" \
"./data/torch/wiki-w=0-d=3-i-m.txt.vecarray" \
dictFile="./data/torch/dict-hash.txt" \
memHashFreqCutoff=10000
```
...is not working?

**Comment by AndreaAI** [comment]
Yes I downloaded processed data too, but I wanted to run all the process because later I want to try the model with another data.

Exactly what you said, everything works fine until running `build_hash.sh`. I wrote 

`
th ../../scripts/build_hash.lua params \
"./data/torch/wiki-w=0-d=3-i-m.txt.hash" \
"./data/torch/wiki-w=0-d=3-i-m.txt.vecarray" \
"./data/torch/dict-hash.txt" \
memHashFreqCutoff=10000
`
without "dictFile=" and it does something more but there is still a problem with function `build_load_dict(fname)`, because when it does     

`local f = io.open(fname)
 local t = f:read("*all")
`
I printed t and it reads the file, but when it does 
`
    while true do
        local s = f:read("*line")
        ......
`
it doesn't read the line because if I print s, it said is nil.

Another question, when is `./data/torch/wiki-w=0-d=3-i-m.txt.hash` created?

**Comment by AndreaAI** [comment]
I downloaded to the processed data but I wanted to run all the steps because later I want to try the model with another data.

I think now it is working perfectly, I'm going to try now to train the model. I made a mistake while copying the build_hash.lua code and I didn't notice. Sorry for losing your time and really thank you so much for your help!

**Comment by alexholdenmiller** [comment]
Oh good I'm glad it's all working!

**Comment by ghost** [comment]
hello how to build hashed memories from kb? I couldn't find a script for it
