### ISSUE TITLE
Why use element-wise sum rather than concatenate these features?

### ISSUE THREAD

**Issue by ruizhaogit** [facebook/MemNN#6]
Hi MemNN authors (@tesatory) ,

Thank you for the great code!
I have a question regarding this [line](https://github.com/facebook/MemNN/blob/master/MemN2N-lang-model/model.lua#L21). Why do you use element-wise sum rather than concatenate these two features and feed it to a fully connected layer? Is there any advantages using the element-wise sum?

Thank you!

Best,
Rui

**Comment by tesatory** [comment]
Addition is more generic than concatenation in this case. Probably concatenation would work too. There is not much difference I think.

**Comment by ruizhaogit** [comment]
Good to know! Thanks!
